
[general]
	#Scaling speed in ticks per unit of scale change. (default 20)
	#Range: > 1
	scale_speed = 20
	#Whether items have detailed descriptions. Disable if you hate information.
	description_enable = true

[items]

	#Change item scaling
	[items.scaling]
		#(default 2.0)
		#Range: 0.01 ~ 32.0
		band_generic_scale = 2.0
		#(default 1.5)
		#Range: 0.01 ~ 32.0
		lesser_band_generic_scale = 1.5
		#(default 0.65)
		#Range: 0.01 ~ 32.0
		shrink_band_generic_scale = 0.5
		#(default 2.0)
		#Range: 0.01 ~ 32.0
		band_globetrotters_scale = 2.0
		#maximum possible scale (default 16.0)
		#Range: 0.01 ~ 32.0
		band_globetrotters_limit_scale = 10.0
		#(default 0.1)
		#Range: 0.01 ~ 32.0
		mask_diminishment_scale = 0.1

	#Mask of Diminishment settings
	[items.mask_diminishment]
		#Whether having items in the inventory reduces scaling. (default true)
		mask_diminishment_special = true

	#Ancient Globetrotter's Band settings
	[items.ancient_globetrotters_band]
		#Maximum amount of time a globetrotter's band can accumulate; when this value is reached the player will be set to the limit scale. This value increases by 1 every 5 seconds. (default 72000)
		#Range: > 1
		band_globetrotters_limit = 72000
		#Amount to increase all damage by when equipping. (default -0.9)
		#Range: -3.4028234663852886E38 ~ 3.4028234663852886E38
		band_globetrotters_damage = -0.9

	#False Hand settings
	[items.false_hand]
		#Amount of flat damage resistance added when equipping while flipped (default -2.0)
		#Range: -3.4028234663852886E38 ~ 3.4028234663852886E38
		false_hand_flat_resistance = -2.0
		#Amount of time for a flipped false hand to flip back, in seconds. (default 180)
		#Range: > 1
		false_hand_time = 180

	[items.marks]
		#Duration of the regen-blocking debuff applied when removing marks, in ticks. (default 200)
		#Range: > 1
		marks_duration = 200
		#Whether marked players have their chat messages colored. (default true)
		marks_color_chat = true

		#Mark of the Descended settings
		[items.marks.mark_descended]
			#Duration of the Strains of Ascent effect when applied. (default 100)
			#Range: > 1
			mark_descended_duration = 100
			#Amount of blocks to ascend before Strains of Ascent is applied. (default 5)
			#Range: > 1
			mark_descended_ascend = 5
			#Amount of armor to add when equipping. (default 6)
			#Range: > -2147483648
			mark_descended_armor = 6
			#Amount to add to the player's regeneration when equipping. (default 0.5)
			#Range: -3.4028234663852886E38 ~ 3.4028234663852886E38
			mark_descended_regeneration = 0.5

		#Mark of the Faded settings
		[items.marks.mark_faded]
			#Amount to add to the player's healing when equipping. (default -0.25)
			#Range: -3.4028234663852886E38 ~ 3.4028234663852886E38
			mark_faded_healing = -0.25
			#Amount to increase the player's damage by when equipping. (default 0.5)
			#Range: -3.4028234663852886E38 ~ 3.4028234663852886E38
			mark_faded_damage = 0.5
			#Amount of flat damage resistance added when equipping. (default 2.0)
			#Range: -3.4028234663852886E38 ~ 3.4028234663852886E38
			mark_faded_flat_resistance = 2.0

		#Mark of the Forgotten settings
		[items.marks.mark_forgotten]
			#Duration to apply the health-bar-hiding effect when getting hit, in ticks. (default 100)
			#Range: > 1
			mark_forgotten_duration = 100
			#Amount to add to the player's critical damage when equipping. (default 0.5)
			#Range: -3.4028234663852886E38 ~ 3.4028234663852886E38
			mark_forgotten_critical_damage = 0.5
			#Amount to add to the player's damage resistance when equipping. (default 0.15)
			#Range: -3.4028234663852886E38 ~ 3.4028234663852886E38
			mark_forgotten_resistance = 0.15

		#Mark of the Judged settings
		[items.marks.mark_judged]
			#Duration of the strength effect applied to nearby mobs. (default 300)
			#Range: > 1
			mark_judged_duration = 300
			#Amount to increase all attack damage by when equipping. (default 4.0)
			#Range: -3.4028234663852886E38 ~ 3.4028234663852886E38
			mark_judged_damage = 4.0
			#Amount to increase speed by when equipping. (default 0.1)
			#Range: -3.4028234663852886E38 ~ 3.4028234663852886E38
			mark_judged_speed = 0.1

		#Mark of the Purified settings
		[items.marks.mark_purified]
			#Ratio of health added per armor point. (default 1.0)
			#Range: -3.4028234663852886E38 ~ 3.4028234663852886E38
			mark_purified_ratio = 1.0
			#Ratio of health added per armor toughness point. (default 1.0)
			#Range: -3.4028234663852886E38 ~ 3.4028234663852886E38
			mark_purified_ratio_tough = 1.0

		#Mark of the Unknown settings
		[items.marks.mark_unknown]
			#Amount to add or remove healing by. (default 0.25)
			#Range: 0.0 ~ 3.4028234663852886E38
			mark_unknown_healing = 0.25
			#Amount to add or remove all incoming damage by. (default 0.75)
			#Range: 0.0 ~ 3.4028234663852886E38
			mark_unknown_flat_resistance = 0.75
			#Upper/lower limit of speed changes. (default 0.5)
			#Range: 0.0 ~ 3.4028234663852886E38
			mark_unknown_speed = 0.5
			#Upper/lower limit of max health changes; upper limit is doubled. (default 10)
			#Range: > 0
			mark_unknown_health = 10
			#Amount of time before the mark's stats are randomized again. (default 300)
			#Range: > 1
			mark_unknown_time = 300

		#Mark of the Obliterated settings
		[items.marks.mark_obliterated]
			#Amount to increase the player's damage by when equipping. (default 1.0)
			#Range: -3.4028234663852886E38 ~ 3.4028234663852886E38
			mark_obliterated_damage = 1.0
			#Amount to increase the player's knockback dealt when equipping. (default 1.0)
			#Range: -3.4028234663852886E38 ~ 3.4028234663852886E38
			mark_obliterated_knockback = 1.0
			#Amount to add to the player's armor when equipping. (default 8)
			#Range: > -2147483648
			mark_obliterated_armor = 8
			#Amount to add to the player's armor toughness when equipping. (default 8)
			#Range: > -2147483648
			mark_obliterated_armor_toughness = 8
			#Amount to add to the player's max health when equipping. (default 10)
			#Range: > -2147483648
			mark_obliterated_health = 10

