
[general]
	disable_mod = false
	space_modules = false
	shadow_text = true
	animations = true
	animationSpeed = 3.0
	background_color = 1867534416

[[modules_left]]
	name = "fps"
	color_high = 5635925
	color_med = 16777045
	color_low = 16733525
	enabled = true

	[modules_left.lines]
		fps = true

[[modules_left]]
	name = "empty"
	enabled = true

	[modules_left.lines]
		nothing = true

[[modules_left]]
	name = "system"
	name_color = 11184810
	value_color = 5636095
	enabled = true

	[modules_left.lines]
		java_version = false
		memory_usage = true
		allocated_memory = true
		cpu = false
		display = true
		gpu = false
		opengl_version = false
		gpu_driver = false

[[modules_left]]
	name = "empty"
	enabled = true

	[modules_left.lines]
		nothing = true

[[modules_left]]
	name = "entity"
	name_color = 16733695
	value_color = 16777045
	enabled = true

	[modules_left.lines]
		particles = false
		entities = true
		monster = true
		creature = true
		ambient = false
		water_creature = false
		water_ambient = false
		misc = false
		axolotls = false
		underground_water_creature = false

[[modules_left]]
	name = "entity"
	name_color = 11141290
	value_color = 16777045
	enabled = true

	[modules_left.lines]
		particles = true
		entities = false
		monster = false
		creature = false
		ambient = false
		water_creature = false
		water_ambient = false
		misc = false
		axolotls = false
		underground_water_creature = false

[[modules_left]]
	name = "sound"
	name_color = 11141290
	value_color = 16777045
	enabled = true

	[modules_left.lines]
		sounds = true
		ambient_sounds = false

[[modules_left]]
	name = "empty"
	enabled = true

	[modules_left.lines]
		nothing = true

[[modules_left]]
	name = "coords"
	name_color = 16755200
	color_x = 16217975
	color_y = 8454016
	color_z = 8454143
	enabled = true

	[modules_left.lines]
		player_coords = true
		block_coords = true
		chunk_relative_coords = false
		chunk_coords = true

[[modules_left]]
	name = "empty"
	enabled = true

	[modules_left.lines]
		nothing = true

[[modules_left]]
	name = "location"
	name_color = 43520
	value_color = 16777045
	enabled = true

	[modules_left.lines]
		dimension = true
		facing = true
		rotation = true
		light = true
		light_server = true
		highest_block = false
		highest_block_server = false
		biome = true
		local_difficulty = false
		days_played = true

[[modules_left]]
	name = "empty"
	enabled = true

	[modules_left.lines]
		nothing = true

[[modules_left]]
	name = "chunks"
	name_color = 11985658
	value_color = 16777045
	enabled = true

	[modules_left.lines]
		chunk_sections = false
		chunk_culling = false
		pending_chunks = false
		pending_uploads = false
		available_buffers = false
		client_chunk_cache = true
		loaded_chunks = true
		loaded_chunks_server = true
		forceloaded_chunks = true
		spawn_chunks = true

[[modules_right]]
	name = "minecraft"
	name_color = 43520
	value_color = 5636095
	enabled = true

	[modules_right.lines]
		minecraft = true

[[modules_right]]
	name = "system"
	name_color = 16777215
	value_color = 5636095
	enabled = true

	[modules_right.lines]
		java_version = true
		memory_usage = false
		allocated_memory = false
		cpu = false
		display = false
		gpu = false
		opengl_version = false
		gpu_driver = false

[[modules_right]]
	name = "empty"
	enabled = true

	[modules_right.lines]
		nothing = true

[[modules_right]]
	name = "server"
	name_color = 11184810
	value_color = 16777045
	enabled = true

	[modules_right.lines]
		server_tick = true
		packets_sent = true
		packets_received = true

[[modules_right]]
	name = "empty"
	enabled = true

	[modules_right.lines]
		nothing = true

[[modules_right]]
	name = "target"
	name_color = 16733695
	value_color = 16777045
	enabled = true

	[modules_right.lines]
		targeted_block = false
		id_block = false
		block_states = false
		block_tags = false
		nothing = false
		targeted_fluid = false
		id_fluid = false
		fluid_states = false
		fluid_tags = false
		nothing2 = false
		targeted_entity = true

[[modules_right]]
	name = "empty"
	enabled = true

	[modules_right.lines]
		nothing = true

[[modules_right]]
	name = "target"
	name_color = 16755200
	value_color = 16777045
	enabled = true

	[modules_right.lines]
		targeted_block = true
		id_block = true
		block_states = true
		block_tags = false
		nothing = false
		targeted_fluid = false
		id_fluid = false
		fluid_states = false
		fluid_tags = false
		nothing2 = false
		targeted_entity = false

[[modules_right]]
	name = "empty"
	enabled = true

	[modules_right.lines]
		nothing = true

[[modules_right]]
	name = "target"
	name_color = 43690
	value_color = 16777045
	enabled = true

	[modules_right.lines]
		targeted_block = false
		id_block = false
		block_states = false
		block_tags = false
		nothing = false
		targeted_fluid = true
		id_fluid = true
		fluid_states = true
		fluid_tags = false
		nothing2 = false
		targeted_entity = false

[[modules_right]]
	name = "empty"
	enabled = true

	[modules_right.lines]
		nothing = true

[[modules_right]]
	name = "target"
	name_color = 16755200
	value_color = 16777045
	enabled = true

	[modules_right.lines]
		targeted_block = false
		id_block = false
		block_states = false
		block_tags = true
		nothing = true
		targeted_fluid = false
		id_fluid = false
		fluid_states = false
		fluid_tags = false
		nothing2 = false
		targeted_entity = false

[[modules_right]]
	name = "empty"
	enabled = true

	[modules_right.lines]
		nothing = true

[[modules_right]]
	name = "target"
	name_color = 43690
	value_color = 16777045
	enabled = true

	[modules_right.lines]
		targeted_block = false
		id_block = false
		block_states = false
		block_tags = false
		nothing = false
		targeted_fluid = false
		id_fluid = false
		fluid_states = false
		fluid_tags = true
		nothing2 = false
		targeted_entity = false

