
#General settings
[general]
	#Only operator permission can use this mod? if false, all player can use this mod
	op_only = true
	#Enable custom path.
	enable_custom_path = true
	#please write the correct custom path
	custom_path = "C:\\Users\\Guildes\\AppData\\Roaming\\.minecraft\\CurseForge\\Instances\\O Flabuoso Fábio\\global"

